endpoints:
  shutdown:
    sensitive: false
    enabled: true

logging:
  file:
    name: app.log
#    path: ./logs
  level:
    root: INFO
    web: DEBUG
    com.sas: DEBUG
    com.codexsoft.sas: DEBUG

spring:
  jackson:
    serialization:
      write_dates_as_timestamps: false
      order_map_entries_by_keys: true
      indent_output: true
      wrap_exceptions: true

swagger:
  # host/port to use in Swagger interface; all request from the interface will use it
  host: user:codex123@104.198.187.78:80
  # host: localhost:8080
  auth:
    enabled: true
    users:
      user1: password
      user2: password2

server:
  # a port to launch proxy at
  port: 8443
  port.http: 8080
  ssl:
    key-alias: selfsigned_localhost_sslserver
    key-store: classpath:localhost-ssl-keystore.p12
    key-store-type: PKCS12
    key-store-password: sas9api
    key-password: sas9api
    enabled: true

proxy:
  sas:
    # Required: SASHome folder of SAS installation
    sashome: /home/eugene/Documents/SAS/sas-libraries/SASHome
  # Required: default workspace server name
  default_workspace_server_name: SASApp
  # Optional: SASApi auth methods
  apikeyEnabled: false
  basicAuthEnabled: false
  # Required: a list of metadata servers and their connection details
  servers:
    - # server alias name to use in endpoints that require it
      name: test
      # metadata server host address
      host: sas.analytium.co.uk
      # metadata server port
      port: 8561
      # list of users and credentials
      users:
        - # user name
          name: sasdev
          # user password
          password: DevelopingSASSolutions1
          key: GermanySchedulingUser
        - name: sasadm
          password: DevelopingSASSolutions
          key: BelgiumBatchUser
    - name: prod
      host: sas.analytium.co.uk
      port: 8571
      users:
        - name: sasdev1
          password: DevelopingSASSolutions
          key: GermanySchedulingUser1
        - name: sasadm1
          password: Develop1ingSASSolutions
          key: BelgiumBatchUser

#DataSetData config
datasetdata:
  max_fetch_size: 10000
  default_fetch_size: 100
